baseURL = "https://jrcampo.com/"
title = "jrcampo"
theme = "mana"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
  pageSize = 10

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    style = "catppuccin-macchiato"

[outputs]
  home = ["HTML", "JSON"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  enableIntegrity = false
  relatedPostsCount = 3
  description = "Cybersecurity Engineer from Galicia, Spain"
  author = "Javier Rodriguez Campo"
  heroTitleLine1 = "JAVIER RODRÍGUEZ"
  heroTitleLine2 = "CYBERSECURITY ENGINEER"

  [params.avatar]
    url = "/curriculum.png"

  [params.social]
    github = "https://github.com/javirodriguezzz"
    linkedin = "https://www.linkedin.com/in/jrcampo"
    twitter = "jrodriguezz24"
    email = "javi.rodrgz@gmail.com"

  [params.buyMeACoffee]
    enabled = false
    id = ""

  [params.codeHighlight]
    darkTheme = "catppuccin-macchiato"
    lightTheme = "catppuccin-frappe"

  [params.copyright]
    startYear = 2022
    owner = "Javier Rodriguez Campo"

  [params.admonitions]
    alertStyle = "favicon"

[[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[menus.main]]
  name = "Experience"
  url = "/experience/"
  weight = 20

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 30

[[menus.main]]
  name = "Posts"
  pageRef = "/posts"
  weight = 40

[[menus.main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 50
